### ISSUE TITLE
Compiling on Linux Mint 18.2

### ISSUE THREAD

**Issue by macramole** [machmach/gphoto2-liveview-example#1]
This is for required sdl libraries:
sudo apt install libsdl2-dev libsdl2-image

I had to change the order of parameters in order to compile:
gcc main.c -O2 -std=c99 -lSDL2 -lSDL2_image -o gphoto2-liveview-example

**Comment by aqiank** [comment]
Thanks, I've updated the Makefile. Hopefully it works for your system now.
